# Generated by Django 4.2.3 on 2023-08-08 10:09

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=100, validators=[common.validators.only_letters_validator]),
        ),
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.CharField(max_length=100, validators=[common.validators.only_letters_validator]),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_name',
            field=models.CharField(max_length=100, validators=[common.validators.only_letters_validator]),
        ),
    ]
