# Generated by Django 4.2.3 on 2023-08-01 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_order_apartment_building_order_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='phone_numbe',
            new_name='phone_number',
        ),
    ]
