# Generated by Django 4.2.3 on 2023-08-02 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_rename_phone_numbe_order_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('courier', 'With Courier'), ('self_delivery', 'Delivered by Us (for Sofia)')], default=None, max_length=100),
            preserve_default=False,
        ),
    ]
