services:
  web:
    image: danieii/rocco-woodwork
    command: gunicorn --bind=0.0.0.0:8000 RoccoWoodwork.wsgi
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    volumes:
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    depends_on:
      - db
    restart: always

  db:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt/live/roccowoodwork.com/fullchain.pem:/etc/letsencrypt/live/roccowoodwork.com/fullchain.pem
      - /etc/letsencrypt/live/roccowoodwork.com/privkey.pem:/etc/letsencrypt/live/roccowoodwork.com/privkey.pem

volumes:
  postgres_data:
