# Generated by Django 4.2.3 on 2023-09-12 17:12

from django.db import migrations


def remove_backslash_before_comma(apps, schema):
    Product = apps.get_model("products", "Product")

    for product in Product.objects.all():
        product.description = product.description.replace("\\,", ",")
        product.save()


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_auto_20230912_2012"),
    ]

    operations = [migrations.RunPython(remove_backslash_before_comma)]
