# Generated by Django 4.2.3 on 2023-08-29 23:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0010_alter_product_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
