# Generated by Django 4.2.3 on 2023-07-30 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='nothing', upload_to='blog_images'),
            preserve_default=False,
        ),
    ]
