# Generated by Django 4.2.3 on 2023-08-03 20:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='date_added',
            new_name='created_on',
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
