# Generated by Django 4.2.3 on 2023-09-14 10:44

import common.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, validators=[common.validators.only_letters_validator], verbose_name='Име')),
                ('last_name', models.CharField(max_length=100, validators=[common.validators.only_letters_validator], verbose_name='Фамилия')),
                ('city', models.CharField(max_length=100, validators=[common.validators.only_letters_validator], verbose_name='Град')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('apartment_building', models.CharField(blank=True, max_length=100, null=True, verbose_name='Апартамент, блок и т.н')),
                ('postal_code', models.IntegerField(verbose_name='Пощенски код')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(error_messages={'invalid': 'Въведете валиден телефонен номер'}, max_length=128, region=None, verbose_name='Телефонен номер')),
                ('email', models.EmailField(max_length=254, verbose_name='Имейл')),
                ('delivery_type', models.CharField(choices=[('', 'Вид доставка'), ('courier', 'С куриер: 7.00 лв.'), ('self_delivery', 'Лично предаване (за гр. София)')], default='', max_length=100)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Бележки към поръчката (относно доставката или друго)')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SavedCheckoutInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, validators=[common.validators.only_letters_validator])),
                ('last_name', models.CharField(max_length=100, validators=[common.validators.only_letters_validator])),
                ('city', models.CharField(max_length=100, validators=[common.validators.only_letters_validator])),
                ('address', models.CharField(max_length=100)),
                ('apartment_building', models.CharField(max_length=100, null=True)),
                ('postal_code', models.IntegerField()),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(max_length=254)),
                ('delivery_type', models.CharField(max_length=100)),
            ],
        ),
    ]
