# Generated by Django 4.2.3 on 2023-08-20 20:32

import common.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_savedcheckoutinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='order',
            name='apartment_building',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Апартамент, блок и т.н'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=100, validators=[common.validators.only_letters_validator], verbose_name='Град'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('', 'Вид доставка'), ('courier', 'С куриер: 7.00 лв.'), ('self_delivery', 'Лично предаване (за гр. София)')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Имейл'),
        ),
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.CharField(max_length=100, validators=[common.validators.only_letters_validator], verbose_name='Име'),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_name',
            field=models.CharField(max_length=100, validators=[common.validators.only_letters_validator], verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Телефонен номер'),
        ),
        migrations.AlterField(
            model_name='order',
            name='postal_code',
            field=models.IntegerField(verbose_name='Пощенски код'),
        ),
    ]
