# Generated by Django 4.2.3 on 2023-08-29 23:38

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_order_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Бележки към поръчката (относно доставката или друго)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(error_messages={'invalid': 'Въведете валиден телефонен номер'}, max_length=128, region=None, verbose_name='Телефонен номер'),
        ),
    ]
