# Generated by Django 4.2.3 on 2023-09-02 19:18

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_alter_order_notes_alter_order_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedcheckoutinformation',
            name='order',
        ),
        migrations.AddField(
            model_name='savedcheckoutinformation',
            name='address',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savedcheckoutinformation',
            name='apartment_building',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='savedcheckoutinformation',
            name='city',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savedcheckoutinformation',
            name='delivery_type',
            field=models.CharField(default='courier', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savedcheckoutinformation',
            name='email',
            field=models.EmailField(default='gosho@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savedcheckoutinformation',
            name='first_name',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savedcheckoutinformation',
            name='last_name',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savedcheckoutinformation',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='savedcheckoutinformation',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='08875269658', max_length=128, region=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savedcheckoutinformation',
            name='postal_code',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
    ]
