# Generated by Django 4.2.3 on 2023-09-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_remove_savedcheckoutinformation_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedcheckoutinformation',
            name='notes',
        ),
        migrations.AddField(
            model_name='order',
            name='number',
            field=models.CharField(blank=True, null=True),
        ),
    ]
