version: "3.4"

services:
  web:
    image: danieii/name
    platform: linux/amd64
    build: .
    command: gunicorn --bind=0.0.0.0:8000 name.wsgi
    working_dir: /app
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    volumes:
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    depends_on:
      - db
      - redis

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: name_db
      PGDATA: /var/lib/postgresql/data/pgdata
    env_file:
      - ./.env
    volumes:
      - ./postgresql:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  nginx:
    image: nginx
    ports:
      - "81:80"
      - "443:443"
    volumes:
      - ./staticfiles:/app/staticfiles
      - ./media:/home/app/web/media
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    links:
      - web
