version: "3.8"

services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - "./:/app/"
    depends_on:
      - db
      - redis

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - "./postgresql:/var/lib/postgresql/data"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
