# Generated by Django 4.2.3 on 2023-09-12 17:16

from django.db import migrations
import os


def add_product_images(apps, schema_editor):
    Product = apps.get_model("products", "Product")
    ProductImage = apps.get_model("products", "ProductImage")
    ProductImage.objects.all().delete()

    for product in Product.objects.all():
        slug = product.slug
        slug_parts = slug.split("-")
        id = slug_parts[-1]
        slug = "-".join(slug_parts[:-1]) + f"-{int(id) + 94}"

        image_directory = os.path.join("media", "product_images")

        image_files = os.listdir(image_directory)

        matching_images = sorted(
            [file for file in image_files if slug in file], key=lambda x: len(x)
        )

        product_images = []

        for image_filename in matching_images:
            product_images.append(
                ProductImage(product=product, image=f"product_images/{image_filename}")
            )

        ProductImage.objects.bulk_create(product_images)


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_auto_20230912_2012"),
    ]

    operations = [migrations.RunPython(add_product_images)]
