# Generated by Django 4.2.3 on 2023-08-29 23:38

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, error_messages={'invalid': 'Въведете валиден телефонен номер'}, max_length=128, null=True, region=None, unique=True),
        ),
    ]
