# Generated by Django 4.2.3 on 2024-10-11 15:37

import common.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, validators=[common.validators.only_alpha], verbose_name='Име')),
                ('last_name', models.CharField(max_length=100, validators=[common.validators.only_alpha], verbose_name='Фамилия')),
                ('city', models.CharField(max_length=100, validators=[common.validators.only_alpha], verbose_name='Град')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('email', models.EmailField(max_length=254, verbose_name='Имейл')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(error_messages={'invalid': 'Въведете валиден телефонен номер'}, max_length=128, region=None, verbose_name='Телефонен номер')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Бележки към поръчката (относно доставката или друго)')),
                ('number', models.CharField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Поръчка',
                'verbose_name_plural': 'Поръчки',
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
