# Generated by Django 4.2.3 on 2024-11-30 14:36

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='additional_information',
            field=models.TextField(blank=True, null=True, verbose_name='Допълнителна информация'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Завършена поръчка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=100, validators=[common.validators.only_alpha], verbose_name='Населено място'),
        ),
    ]
