# Generated by Django 4.2.3 on 2024-12-01 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_order_additional_information_order_is_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('Офис на куриер', 'Доставка до офис на куриер - Еконт'), ('Адрес на получател', 'Доставка до адрес на получател')], default=1, max_length=18, verbose_name='Начин на доставка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='additional_information',
            field=models.TextField(blank=True, null=True, verbose_name='Пояснения към поръчката'),
        ),
    ]
