# Generated by Django 4.2.3 on 2023-07-17 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_price_product__price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='_price',
            new_name='price',
        ),
    ]
