# Generated by Django 4.2.2 on 2023-06-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_category_product_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='nishto', upload_to='product_images/'),
            preserve_default=False,
        ),
    ]
