# Generated by Django 4.2.2 on 2023-07-02 20:57

import django.core.validators
from django.db import migrations, models
import products.validators


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(5), products.validators.validate_first_character]),
        ),
    ]
