# Generated by Django 4.2.3 on 2023-08-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pre_order',
            field=models.BooleanField(default=False),
        ),
    ]
